- defaults:
    shell:
        stdin : true
        stdout: true
        quiet : false

- shell:
    - [sudo apt update && sudo apt install software-properties-common && sudo apt-add-repository --yes --update ppa:ansible/ansible && sudo apt install ansible, Installing ansible]

