# cat with color syntax
- defaults:
    shell:
        stdin : true
        stdout: true
        quiet : false
    link:
        create: true
        relink: true
        force: true

# - shell:
    # - [./scripts/installation/bat.sh, Installing bat] # better install with zinit
- link:
    ~/.config/bat/config : bat/bat.conf
