# Install essential packages
- defaults:
    shell:
        stdin : true
        stdout: true
        quiet : false

- shell:
    - ['find . -type f -iname "*.sh" -exec chmod +x {} \;', Make scripts executable]
    - [./scripts/installation/default.sh, Installing Default]
- link:
      ~/.ignore: ignore

