# Install essential packages

- link:
    ~/.gitconfig : git/gitconfig
    ~/.gitignore : git/gitignore
    ~/.tigrc     : git/tigrc

- shell:
    - ['find . -type f -iname "*.sh" -exec chmod +x {} \;', Make scripts executable]
    - [./scripts/installation/default.sh, Installing Default]
