- defaults:
    shell:
        stdin : true
        stdout: true
        quiet : false
    link:
        create: true
        relink: true

- shell:
    - [sudo apt install direnv, Installing direnv]

- link:
    ~/.config/direnv/direnvrc : direnv/direnvrc

