- defaults:
    shell:
        stdin : true
        stdout: true
        quiet : false
    link:
        create: true
        relink: true

- shell:
    - [./scripts/installation/docker.sh, Installing Docker]

