- defaults:
    shell:
        stdin : true
        stdout: true
        quiet : false

- shell:
    - [./scripts/installation/gcp.sh, Installing gcloud]
      # after installation run: gcloud init to setup gcloud environment (dotbot does not support interactive command)
