# Install essential packages
- defaults:
    shell:
        stdin : true
        stdout: true
        quiet : false
    link:
        create: true
        relink: true
        force: true

- shell:
    - ['apt-fast install --no-install-recommends -y tig', Installing tig]
    - ['git submodule update --init --recursive', Updating git submodule]

- link:
    ~/.gitconfig : git/.gitconfig
    ~/.gitignore : git/.gitignore
    ~/.tigrc     : git/tigrc

