# Install essential packages
- defaults:
    shell:
        stdin : true
        stdout: true
        quiet : false
    link:
        create: true
        relink: true
        force: true

- shell:
    - ['apt-fast install --no-install-recommends -y tig', Installing tig]
    # diff-so-fancy: prettier git diff not necessary as tig is more convenient
    # - ['rm ~/bin/diff-so-fancy && wget https://raw.githubusercontent.com/so-fancy/diff-so-fancy/master/third_party/build_fatpack/diff-so-fancy -O ~/bin/diff-so-fancy && chmod +x ~/bin/diff-so-fancy', Installing diff-so-fancy]

- link:
    ~/.gitconfig : git/gitconfig
    ~/.gitignore : git/gitignore
    ~/.tigrc     : git/tigrc

