- defaults:
    shell:
        stdin : true
        stdout: true
        quiet : false

- shell:
    - [curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash, Installing helm]
