- defaults:
    shell:
        stdin : true
        stdout: true
        quiet : false

- shell:
    - ["curl -L https://github.com/jenkins-zh/jenkins-cli/releases/latest/download/jcli-linux-amd64.tar.gz|tar xzv && sudo mv jcli /usr/local/bin/", Installing jenkins-cli]

