- defaults:
    shell:
        stdin : true
        stdout: true
        quiet : false

- shell:
    - ["curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl", Installing kubectl]
    - ["chmod +x ./kubectl && sudo mv ./kubectl /usr/local/bin/kubectl", Setup bin file]

