- defaults:
    shell:
        stdin : true
        stdout: true
        quiet : false

- shell:
    - ["rm -f kustomize && curl -s 'https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh' | bash && mv kustomize $DOTFILES_BIN_DIR", Installing kustomize]
        # https://kubectl.docs.kubernetes.io/installation/kustomize/binaries/
        # The following script detects your OS and downloads the appropriate kustomize binary to your current working directory.
        # This script doesn’t work for ARM architecture. If you want to install ARM binaries, please go to the release page to find the URL.

