- defaults:
    shell:
        stdin : true
        stdout: true
        quiet : false
    link:
        create: true
        relink: true
        force: true

- shell:
    - [./scripts/installation/nvim.sh, Installing NeoVim]

- link:
    ~/.config/nvim/init.vim       : nvim/init.vim
    ~/.config/nvim/conf           : nvim/conf
    ~/.config/nvim/after/ftplugin : nvim/ftplugin
    ~/.config/nvim/snippets       : nvim/snippets
    ~/.ctags                      : nvim/conf/ctags
    ~/.config/TabNine/tabnine_config.json : nvim/coc/extensions/tabnine_config.json

