- defaults:
    link:
        create: true
        relink: true
    shell:
        stdin : true
        stdout: true
        quiet : false

- link:
    ~/.config/nvim/init.vim       : nvim/init.vim
    ~/.config/nvim/conf           : nvim/conf
    ~/.config/nvim/after/ftplugin : nvim/ftplugin
    ~/.config/nvim/snippets       : nvim/snippets
    ~/.ctags                      : nvim/ctags

- shell:
    - [./scripts/installation/nvim.sh, Installing NeoVim]

