- defaults:
    shell:
        stdin : true
        stdout: true
        quiet : false
    link:
        create: true
        relink: true
        force: true

- shell:
    - ['sudo apt-fast install --no-install-recommends -y openvpn network-manager-openvpn network-manager-openvpn-gnome', Installing OpenVpn]

