- defaults:
    shell:
        stdin : true
        stdout: true
        quiet : false
- shell:
    # default Shutter delivered by package manager use old version and miss some important features (such as edit screenshot)
    - ['sudo add-apt-repository -y ppa:linuxuprising/shutter && sudo apt-get update && apt-fast install --no-install-recommends -y shutter', Installing Shutter]
