- defaults:
      shell:
          stdin: true
          stdout: true
          quiet: false
      link:
          create: true
          relink: true
          force: true
- shell:
    - [./scripts/installation/tldr.sh, Installing tldr]
