- defaults:
    link:
        create: true
        relink: true
    shell:
        stdin : true
        stdout: true
        quiet : false

- clean: ['~']

- shell:
    - [./scripts/installation/tmux.sh, Installing TMUX]

- link:
    ~/.tmux.conf : tmux/tmux.conf
    ~/.tmuxp     : tmux/tmuxp

