- defaults:
    shell:
        stdin : true
        stdout: true
        quiet : false
    link:
        create: true
        relink: true
        force: true

- shell:
    - [./scripts/installation/vim.sh, Installing Vim]

- link:
    ~/.vimrc                              : vim/vimrc
    ~/.vim/conf                           : vim/conf
    ~/.vim/after/ftplugin                 : vim/ftplugin
    ~/.vim/snippets                       : vim/snippets
    ~/.ctags                              : vim/conf/ctags
    ~/.vim/coc-settings.json              : vim/coc/coc-settings.json
    ~/.config/TabNine/tabnine_config.json : vim/coc/extensions/tabnine_config.json

