- defaults:
    link:
        create: true
        relink: true
    shell:
        stdin : true
        stdout: true
        quiet : false

- clean: ['~']

- link:
    ~/.zshrc : zsh/zshrc

- shell:
    - [./scripts/installation/zsh.sh, Installing ZSH]
    - ['yes | cp -rf zsh/custom/* ${HOME}/.oh-my-zsh/custom', Setup custom zsh scripts]
    - ['yes | cp -rf scripts ${HOME}/.oh-my-zsh/custom', Setup library for custom zsh scripts]
    - ['source ${HOME}/.zshrc', source zsh shell]

