- defaults:
    link:
        create: true
        relink: true
    shell:
        stdin : true
        stdout: true
        quiet : false

- clean: ['~']

- shell:
    - [./scripts/installation/zsh.sh, Installing ZSH]

# - link: # it could be error prone to link zshrc file, suggest that we clone a new file instead.
#     ~/.zshrc : zsh/zshrc

