version: "3.2"
services:
    # create a container as an environment to test shell scripts
    # ubuntu:
    #     build: .
    #     working_dir: /dotfiles
    #     volumes:
    #         - .:/dotfiles

    plantuml:
        image: plantuml/plantuml-server:jetty
        ports:
            - 8080:8080

