version: '3.2'
services:
  ubuntu: # create a container as an environment to test shell scripts
    build: .
    volumes:
      - .:/dotfiles
      - ~/.ssh:/root/.ssh
    command: "tail -f /var/log/bootstrap.log"
