[General]
  snippetfile = "/home/minh/.config/pet/snippet.toml"
  editor = "vim"
  column = 40
  selectcmd = "fzf"
  backend = "gist"

[Gist]
  file_name = "pet-snippet.toml"
  access_token = "TOKEN"
  gist_id = "2b867fe935db5be4bc61374b630814c9"
  public = false
  auto_sync = true

# [GitLab]
#   file_name = "pet-snippet.toml"
#   access_token = "TOKEN"
#   url = ""
#   id = ""
#   visibility = "private"
#   auto_sync = true
